[package]
name = "ferese-theme"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
jiff.workspace = true
ferese-theme-model = { path = "../ferese-theme-model" }
libcosmic = { workspace = true, features = ["a11y"] }

iced_accessibility = { git = "https://github.com/ferese-wm/libcosmic", rev = "1e28a24acab159a8509dcecd59d9cd4bafe8baa0" }

[dev-dependencies]
ferese-config = { path = "../ferese-config" }
