[workspace]
members = [
    "compositor",
    "feresectl",
    "crates/ferese-animation",
    "crates/ferese-core",
    "crates/ferese-config",
    "crates/ferese-theme",
    "crates/ferese-theme-client",
    "crates/ferese-theme-model",
    "crates/ferese-ipc",
    "crates/ferese-layout",
    "crates/ferese-protocols",
    "shell/ferese-shell",
    "shell/ferese-settings",
    "shell/ferese-lock",
    "shell/ferese-polkit-agent",
    "portal",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.95"

[workspace.dependencies]
ferese-shape = { git = "https://github.com/ferese-wm/ferese-shape", tag = "v0.1.0" }
bitflags = "2.9.4"
calloop = { version = "0.14.4", features = ["signals"] }
jiff = "0.2.37"
libc = "0.2.176"
libcosmic = { git = "https://github.com/ferese-wm/libcosmic", tag = "ferese-v0.1.1", default-features = false, features = ["multi-window", "tokio", "wayland"] }
smithay = { version = "0.7.0", default-features = false, features = [
    "backend_drm",
    "backend_gbm",
    "backend_libinput",
    "backend_session_libseat",
    "backend_udev",
    "backend_winit",
    "desktop",
    "renderer_gl",
    "wayland_frontend",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
xcursor = "0.3.11"
wayland-backend = "0.3.17"
wayland-client = "0.31.15"
wayland-scanner = "0.31.11"
wayland-server = "0.31.14"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
