/* Generated by wayland-scanner 1.26.0 */

/*
 * Copyright 2026 Ferese contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface ferese_shell_v1_interface;

static const struct wl_interface *ferese_shell_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&ferese_shell_v1_interface,
};

static const struct wl_message ferese_shell_manager_v1_requests[] = {
	{ "get_shell", "n", ferese_shell_v1_types + 9 },
	{ "destroy", "", ferese_shell_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface ferese_shell_manager_v1_interface = {
	"ferese_shell_manager_v1", 6,
	2, ferese_shell_manager_v1_requests,
	0, NULL,
};

static const struct wl_message ferese_shell_v1_requests[] = {
	{ "activate_window", "uu", ferese_shell_v1_types + 0 },
	{ "close_window", "uu", ferese_shell_v1_types + 0 },
	{ "activate_workspace", "uu", ferese_shell_v1_types + 0 },
	{ "enter_overview", "", ferese_shell_v1_types + 0 },
	{ "exit_overview", "", ferese_shell_v1_types + 0 },
	{ "select_overview_window", "uu", ferese_shell_v1_types + 0 },
	{ "destroy", "", ferese_shell_v1_types + 0 },
	{ "confirm_logout", "3u", ferese_shell_v1_types + 0 },
	{ "cancel_logout", "3u", ferese_shell_v1_types + 0 },
	{ "confirm_logout_with_inhibitors", "4uuuu", ferese_shell_v1_types + 0 },
};

static const struct wl_message ferese_shell_v1_events[] = {
	{ "snapshot_begin", "u", ferese_shell_v1_types + 0 },
	{ "window", "uuuussu", ferese_shell_v1_types + 0 },
	{ "output", "uusuuu", ferese_shell_v1_types + 0 },
	{ "workspace", "uuuusuuuu", ferese_shell_v1_types + 0 },
	{ "snapshot_end", "u", ferese_shell_v1_types + 0 },
	{ "overview_state", "u", ferese_shell_v1_types + 0 },
	{ "request_failed", "uuus", ferese_shell_v1_types + 0 },
	{ "capabilities", "u", ferese_shell_v1_types + 0 },
	{ "config_begin", "2", ferese_shell_v1_types + 0 },
	{ "config_chunk", "2s", ferese_shell_v1_types + 0 },
	{ "config_end", "2", ferese_shell_v1_types + 0 },
	{ "logout_cancelled", "3u", ferese_shell_v1_types + 0 },
	{ "logout_requested", "3us", ferese_shell_v1_types + 0 },
	{ "toggle_keybinding_guide", "5s", ferese_shell_v1_types + 0 },
	{ "toggle_display_mode", "6s", ferese_shell_v1_types + 0 },
	{ "monitor_state_changed", "6", ferese_shell_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface ferese_shell_v1_interface = {
	"ferese_shell_v1", 6,
	10, ferese_shell_v1_requests,
	16, ferese_shell_v1_events,
};

