[package]
name = "ferese-settings"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ferese-theme-client = { path = "../../crates/ferese-theme-client" }
ferese-theme = { path = "../../crates/ferese-theme" }
ferese-config = { path = "../../crates/ferese-config" }
libcosmic = { workspace = true, features = ["wgpu", "a11y", "xdg-portal"] }
iced_accessibility = { git = "https://github.com/ferese-wm/libcosmic", tag = "ferese-v0.1.1" }
ferese-ipc = { path = "../../crates/ferese-ipc" }
serde_json.workspace = true
tempfile.workspace = true
shlex = "1.3.0"
notify = "8.2.0"
tokio = { version = "1", features = ["sync", "time", "rt"] }
zbus = "5.19.0"
zeroize = "1.9"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "webp"] }
